import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { PageLayout } from '../components/layout/PageLayout';
import { Navbar } from '../components/layout/Navbar';
import { Scale } from 'lucide-react';
import { motion } from 'framer-motion';

const EFFECTIVE_DATE = 'February 28, 2026';

const reveal = {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, amount: 0.2 },
    transition: { duration: 0.45 },
};

const Section = ({ title, children }: { title: string; children: ReactNode }) => (
    <motion.section
        className="space-y-3"
        initial={reveal.initial}
        whileInView={reveal.whileInView}
        viewport={reveal.viewport}
        transition={reveal.transition}
    >
        <h2 className="text-2xl md:text-3xl font-black text-brand-secondary tracking-tight">{title}</h2>
        <div className="space-y-3 text-sm md:text-base text-text-muted leading-relaxed">{children}</div>
    </motion.section>
);

export const TermsPage = () => {
    return (
        <PageLayout header={<Navbar />} maxWidth="full">
            <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 space-y-10">
                <motion.header
                    className="space-y-5"
                    initial={reveal.initial}
                    whileInView={reveal.whileInView}
                    viewport={reveal.viewport}
                    transition={reveal.transition}
                >
                    <div className="page-badge">
                        <Scale size={14} />
                        Terms of Service
                    </div>
                    <h1 className="page-hero-title">Terms of Service</h1>
                    <p className="text-lg text-text-muted max-w-3xl">
                        Effective Date: {EFFECTIVE_DATE}
                    </p>
                    <p className="text-text-muted">
                        These Terms govern your use of Resumit, including resume analysis, AI rewrite, template,
                        GitHub analysis, and export features.
                    </p>
                </motion.header>

                <Section title="1. Acceptance of Terms">
                    <p>
                        By accessing or using the service, you agree to these Terms. If you do not agree, do not use
                        the service.
                    </p>
                </Section>

                <Section title="2. Eligibility and Access">
                    <p>
                        You must have legal capacity to enter into these Terms. You are responsible for how you use the
                        service and for maintaining the confidentiality of any credentials you choose to submit.
                    </p>
                </Section>

                <Section title="3. Permitted Use">
                    <p>You may use the service for lawful career and resume-optimization purposes.</p>
                    <p>You agree not to:</p>
                    <ul className="list-disc pl-5 space-y-1.5">
                        <li>Use the service in violation of law or third-party rights.</li>
                        <li>Upload malicious files, abuse APIs, or attempt unauthorized access.</li>
                        <li>Reverse engineer, disrupt, or overload service infrastructure.</li>
                        <li>Use generated content for fraud, deception, or misrepresentation.</li>
                    </ul>
                </Section>

                <Section title="4. Your Content and Permissions">
                    <p>
                        You retain ownership of content you submit (for example, resumes, job descriptions, and profile
                        text). You grant us a limited license to process that content to operate the features you use.
                    </p>
                    <p>
                        You represent that you have the rights needed to submit your content and that it does not
                        violate law or third-party rights.
                    </p>
                </Section>

                <Section title="5. AI-Generated Output Disclaimer">
                    <p>
                        Outputs are generated by software models and may contain errors, omissions, bias, or outdated
                        assumptions. You are responsible for reviewing and validating all output before use.
                    </p>
                    <p>
                        The service provides career tooling, not legal, employment, or professional certification
                        advice. We do not guarantee interviews, offers, or specific outcomes.
                    </p>
                </Section>

                <Section title="6. Third-Party Services">
                    <p>
                        The service may depend on third-party providers (for example, AI APIs, infrastructure, database
                        services, and GitHub APIs). Their availability and policies may affect service behavior.
                    </p>
                </Section>

                <Section title="7. Fees and Payments">
                    <p>
                        Some features may be paid now or in the future. If paid features are enabled, billing and
                        payment processing may be handled by third-party providers under their own terms.
                    </p>
                </Section>

                <Section title="8. Intellectual Property">
                    <p>
                        The service software, design, branding, and non-user content are owned by Resumit or its
                        licensors and protected by applicable intellectual property laws.
                    </p>
                </Section>

                <Section title="9. Service Availability and Changes">
                    <p>
                        We may modify, suspend, or discontinue any part of the service at any time, including feature
                        availability and access controls.
                    </p>
                </Section>

                <Section title="10. Disclaimer of Warranties">
                    <p>
                        The service is provided on an “as is” and “as available” basis, without warranties of any kind,
                        express or implied, including fitness for a particular purpose, non-infringement, or
                        uninterrupted availability.
                    </p>
                </Section>

                <Section title="11. Limitation of Liability">
                    <p>
                        To the maximum extent permitted by law, Resumit and its operators are not liable for indirect,
                        incidental, consequential, special, exemplary, or punitive damages, or for lost profits, data,
                        opportunities, or business interruption arising from use of the service.
                    </p>
                </Section>

                <Section title="12. Indemnification">
                    <p>
                        You agree to indemnify and hold harmless Resumit and its operators from claims, liabilities, and
                        expenses arising from your misuse of the service, your submitted content, or your violation of
                        these Terms.
                    </p>
                </Section>

                <Section title="13. Termination">
                    <p>
                        We may suspend or terminate access if we reasonably believe you violated these Terms or used the
                        service in a harmful or unlawful way.
                    </p>
                </Section>

                <Section title="14. Governing Law">
                    <p>
                        These Terms are governed by applicable laws of the jurisdiction in which the service operator is
                        established, unless otherwise required by local law.
                    </p>
                </Section>

                <Section title="15. Changes to These Terms">
                    <p>
                        We may update these Terms. Continued use after an update means you accept the revised Terms.
                    </p>
                </Section>

                <Section title="16. Contact">
                    <p>
                        For legal questions, contact: <a className="text-brand-primary font-semibold no-underline hover:underline" href="mailto:tekkdevv@gmail.com">tekkdevv@gmail.com</a>
                    </p>
                </Section>

                <motion.div
                    className="pt-4 border-t border-border-subtle text-sm text-text-muted"
                    initial={reveal.initial}
                    whileInView={reveal.whileInView}
                    viewport={reveal.viewport}
                    transition={reveal.transition}
                >
                    See also our <Link to="/privacy" className="text-brand-primary font-semibold no-underline hover:underline">Privacy Policy</Link>.
                </motion.div>
            </main>
        </PageLayout>
    );
};
